name: auto-update

on:
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: |
          git remote add upstream https://github.com/malgus-waf/class5.git
          git fetch upstream
          git checkout main  # Use 'main' instead of 'master'
          git rebase upstream/main
          git push -f origin main  # Use 'main' instead of 'master'

      
