 name: auto-update
on:
  schedule:
    - cron: '0 */1 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: |
          git remote add upstream https://github.com/malgus-waf/class5.git
          git fetch upstream
          git checkout master
          git rebase upstream/master
          git push -f origin master
      
